name: Generate 3D Contribution Snake

on:
  # Schedule: Har 12 ghante baad auto-run hoga
  schedule:
    - cron: "0 */12 * * *"
  
  # Manual Run ka option
  workflow_dispatch:
  
  # Jab bhi main branch par commit ho
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. Snake animation generate karein
      - name: generate-github-user-contribution-grid-snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 2. Generated SVGs ko 'output' branch par push karein
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
